### PR TITLE
Issue#1 Contact part responsive - fixed

### PR DESCRIPTION
**Pull request by irenejoeunpark**
Fixes to Issue #1 
- Removed unnecessary configurations
- Added image as a content instead of the background
- Divided row4 into two columns for responsive design
- Fixed the width and row 4 works for different sizes 

Hi @mohitbalwani 
I have modified style.css and index.html
It looks like below now

1. width with 1149
Screen Shot 2021-10-29 at 2 36 37 PM

Screen Shot 2021-10-29 at 2 38 17 PM

### CODE REVIEW

**Review by mohitbalwani — CHANGES_REQUESTED** [review]
The contact section is working well now but the services section is breaking on phone view. Try changing flex-direction of services section (i.e. row-2 ) to column using media queries so that I will look like it was previously. Currently it's looking like this
Screenshot 2021-10-30 at 5 45 36 PM

**Comment by irenejoeunpark** [comment]
> The contact section is working well now but the services section is breaking on phone view. Try changing flex-direction of services section (i.e. row-2 ) to column using media queries so that I will look like it was previously. Currently it's looking like this Screenshot 2021-10-30 at 5 45 36 PM

Hi @mohitbalwani , I fixed back row 1,2,3, and now it looks like before.
Thanks! I did not notice those. 

Screen Shot 2021-10-30 at 9 08 16 AM

**Review by mohitbalwani — CHANGES_REQUESTED** [review]
The submit button of contact form is missing.

Screenshot 2021-10-31 at 9 14 15 PM

**Comment by irenejoeunpark** [comment]
Submit button for width under 400px fixed

Screen Shot 2021-10-31 at 6 04 40 PM

**Pull request merged**
